import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Plus } from "lucide-react";
import { requireAuthenticatedUser } from "@/lib/auth";
import { requireAssignedRole } from "@/lib/roles";
import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";
export default async function ApplicationsPage() {
  const user = await requireAuthenticatedUser(); await requireAssignedRole(user.id);
  const supabase = createAdminClient();
  const [{ data, error }, { data: jobs, error: jobsError }] = await Promise.all([supabase.from("job_applications").select("id, first_name, last_name, email, status, submitted_at, job_postings(title)").order("submitted_at", { ascending: false }), supabase.from("job_postings").select("id, title, location, status, updated_at").order("updated_at", { ascending: false })]);
  if (error || jobsError) throw new Error("Unable to load careers administration.");
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold sm:text-3xl">Careers</h1><p className="mt-2 text-neutral-400">Manage job openings and review submitted applications.</p></div><Link href="/admin/applications/jobs/new" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#fb5411] px-4 text-sm font-semibold text-white"><Plus className="size-4" />New job posting</Link></div><section className="mt-8"><h2 className="text-xl font-semibold">Job postings</h2>{jobs?.length ? <div className="mt-4 grid gap-4 sm:grid-cols-2">{jobs.map((job) => <Link key={job.id} href={`/admin/applications/jobs/${job.id}/edit`} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 hover:bg-white/[0.05]"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold text-white">{job.title}</h3><p className="mt-2 text-sm text-neutral-400">{job.location}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs capitalize text-neutral-300">{job.status}</span></div></Link>)}</div> : <p className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-neutral-400">No job postings yet.</p>}</section><section className="mt-10"><h2 className="text-xl font-semibold">Applications</h2>{data?.length ? <div className="mt-4 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="divide-y divide-white/10">{data.map((application) => { const job = Array.isArray(application.job_postings) ? application.job_postings[0] : application.job_postings; return <Link key={application.id} href={`/admin/applications/${application.id}`} className="grid gap-3 p-5 transition hover:bg-white/[0.04] sm:grid-cols-[1.2fr_1fr_150px_40px] sm:items-center"><div><p className="font-semibold text-white">{application.first_name} {application.last_name}</p><p className="mt-1 text-sm text-neutral-400">{application.email}</p></div><p className="text-sm text-neutral-300">{job?.title || "Position"}</p><div><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs capitalize text-neutral-300">{application.status}</span><p className="mt-2 text-xs text-neutral-500">{new Date(application.submitted_at).toLocaleDateString()}</p></div><ArrowRight className="size-5 text-neutral-500" /></Link>; })}</div></div> : <div className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-10 text-center"><BriefcaseBusiness className="mx-auto size-10 text-neutral-500" /><p className="mt-4 text-neutral-400">No applications have been submitted yet.</p></div>}</section></div>;
}
