import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, Download } from "lucide-react";
import { revalidatePath } from "next/cache";
import { requireAuthenticatedUser } from "@/lib/auth";
import { requireAssignedRole } from "@/lib/roles";
import { createAdminClient } from "@/lib/supabase/admin";

const statuses = ["new", "reviewing", "interview", "offer", "hired", "declined"];
async function updateStatus(id: string, formData: FormData) { "use server"; const user = await requireAuthenticatedUser(); await requireAssignedRole(user.id); const status = String(formData.get("status") || ""); if (!statuses.includes(status)) throw new Error("Invalid status."); await createAdminClient().from("job_applications").update({ status, updated_at: new Date().toISOString() }).eq("id", id); revalidatePath(`/admin/applications/${id}`); redirect(`/admin/applications/${id}`); }

export const dynamic = "force-dynamic";
export default async function ApplicationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireAuthenticatedUser(); await requireAssignedRole(user.id); const { id } = await params; const supabase = createAdminClient();
  const { data } = await supabase.from("job_applications").select("*, job_postings(title, slug), job_application_documents(id, document_type, storage_path, file_name, content_type, size_bytes)").eq("id", id).maybeSingle(); if (!data) notFound();
  const documents = await Promise.all((data.job_application_documents || []).map(async (document: { id: string; storage_path: string; file_name: string; document_type: string; size_bytes: number }) => ({ ...document, url: (await supabase.storage.from("job-application-documents").createSignedUrl(document.storage_path, 3600)).data?.signedUrl || "" })));
  const job = Array.isArray(data.job_postings) ? data.job_postings[0] : data.job_postings;
  return <div className="mx-auto max-w-5xl"><Link href="/admin/applications" className="inline-flex items-center gap-2 text-sm text-neutral-400 hover:text-white"><ArrowLeft className="size-4" />Back to applications</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><h1 className="text-3xl font-semibold">{data.first_name} {data.last_name}</h1><p className="mt-2 text-neutral-400">Applied for {job?.title || "Position"} on {new Date(data.submitted_at).toLocaleString()}</p></div><form action={updateStatus.bind(null, id)} className="flex items-end gap-2"><label className="text-xs text-neutral-400">Application status<select name="status" defaultValue={data.status} className="mt-1.5 h-11 rounded-xl border border-white/10 bg-neutral-900 px-4 pr-10 capitalize text-white">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><button className="h-11 rounded-xl bg-[#fb5411] px-4 text-sm font-semibold text-white">Save</button></form></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><Card title="Contact information"><Details rows={[["Email", data.email],["Phone", data.phone],["Address", [data.address, data.city, data.state, data.postal_code].filter(Boolean).join(", ")],["LinkedIn", data.linkedin_url],["Website", data.website_url]]} /></Card><Card title="Eligibility and availability"><Details rows={[["Work authorized", yesNo(data.work_authorized)],["Sponsorship required", yesNo(data.sponsorship_required)],["18 or older", yesNo(data.age_confirmed)],["Available start date", data.start_date],["Desired compensation", data.desired_compensation]]} /></Card><Card title="Experience"><Details rows={[["Most recent employer", data.current_employer],["Most recent title", data.current_title],["Relevant experience", data.years_experience == null ? null : `${data.years_experience} years`],["Education and training", data.education],["Skills and certifications", data.skills],["Referral source", data.referral_source],["Applicant message", data.message]]} /></Card><Card title="Documents">{documents.length ? <div className="space-y-3">{documents.map((document) => <a key={document.id} href={document.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-white/10 p-4 hover:bg-white/5"><div><p className="font-medium text-white">{document.file_name}</p><p className="mt-1 text-xs capitalize text-neutral-500">{document.document_type} · {(document.size_bytes / 1024 / 1024).toFixed(1)} MB</p></div><Download className="size-5 text-neutral-400" /></a>)}</div> : <p className="text-neutral-500">No documents attached.</p>}</Card></div></div>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:p-6"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-5">{children}</div></section>; }
function Details({ rows }: { rows: [string, string | null][] }) { return <dl className="space-y-4">{rows.map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wider text-neutral-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm text-neutral-200">{value || "—"}</dd></div>)}</dl>; }
function yesNo(value: boolean) { return value ? "Yes" : "No"; }
