/* eslint-disable jsx-a11y/alt-text -- react-pdf Image does not support the HTML alt prop */
import { Document, Image, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAuthenticatedUser } from "@/lib/auth";
import { requireAssignedRole } from "@/lib/roles";
import { formatWashingtonDate } from "@/lib/date-time";
import { bidProposalTotal, formatBidCurrency, normalizeBidPricingItems, normalizeBidScopeSections } from "@/lib/bid-proposal";
export const runtime="nodejs"; export const dynamic="force-dynamic";
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}) { const user=await requireAuthenticatedUser(); await requireAssignedRole(user.id); const {id}=await params; const {data:bid}=await createAdminClient().from("bid_opportunities").select("*").eq("id",id).single(); if(!bid?.proposal_drafted_at)return new NextResponse("Proposal not found",{status:404}); const origin=new URL(request.url).origin; const buffer=await renderToBuffer(<Pdf bid={bid} logo={`${origin}/images/paradise_ironworks_logo.png`} />); return new NextResponse(Buffer.from(buffer),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${String(bid.proposal_number||bid.project_name).replace(/[^a-z0-9-]+/gi,"-")}.pdf"`}}); }
function Pdf({bid,logo}:{bid:Record<string,unknown>;logo:string}) { const sections=normalizeBidScopeSections(bid.proposal_scope_sections),items=normalizeBidPricingItems(bid.proposal_pricing_items); const section=(title:string,text:unknown)=>text?<View style={s.section}><Text style={s.heading}>{title}</Text><Text style={s.body}>{String(text)}</Text></View>:null; return <Document><Page size="LETTER" style={s.page}><View style={s.header}><View><Text style={s.company}>PARADISE IRONWORKS &amp; CONSTRUCTION LLC</Text><Text style={s.title}>Commercial Bid Proposal</Text><Text style={s.meta}>Proposal #: {String(bid.proposal_number||"Draft")}</Text><Text style={s.meta}>Date: {formatWashingtonDate(String(bid.proposal_date))}</Text></View>{/* react-pdf Image has no HTML alt prop. */}<Image src={logo} style={s.logo}/></View><View style={s.grid}><View style={s.col}><Text style={s.label}>PROJECT</Text><Text style={s.strong}>{String(bid.project_name)}</Text><Text style={s.body}>{[bid.project_address,bid.city,bid.state,bid.zip_code].filter(Boolean).join(", ")}</Text></View><View style={s.col}><Text style={s.label}>SUBMITTED TO</Text><Text style={s.strong}>{String(bid.proposal_recipient_company||"")}</Text><Text style={s.body}>{String(bid.proposal_recipient_address||"")}</Text><Text style={s.body}>Attention: {String(bid.proposal_attention||"")}</Text></View></View><Text style={[s.body,s.intro]}>{String(bid.proposal_intro||"")}</Text>{sections.map((x,i)=>section(`${i+1}. ${x.title}`,x.content))}<View style={s.section}><Text style={s.heading}>Proposal Price</Text>{bid.proposal_pricing_mode==="line_items"&&items.map((x,i)=><View key={i} style={s.row}><Text>{x.description}</Text><Text>{formatBidCurrency(x.amount||0)}</Text></View>)}<Text style={s.total}>{bid.proposal_pricing_mode==="lump_sum"?"Lump Sum: ":"Total: "}{formatBidCurrency(bidProposalTotal(bid))}</Text></View>{section("Clarifications & Conditions",bid.proposal_clarifications)}{section("Exclusions",bid.proposal_exclusions)}{section("Acknowledged Addenda",bid.proposal_addenda)}{section("Terms",bid.proposal_terms)}<View style={s.footer}><Text>Respectfully,</Text><Text style={s.signature}>{String(bid.proposal_prepared_by||"")}</Text><Text>{String(bid.proposal_prepared_by_title||"")}</Text><Text>Paradise Ironworks &amp; Construction LLC</Text></View></Page></Document>; }
const s=StyleSheet.create({page:{padding:42,fontFamily:"Helvetica",fontSize:9,color:"#171717"},header:{flexDirection:"row",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#d4d4d4",paddingBottom:16},company:{fontSize:8,color:"#737373",letterSpacing:1.2},title:{fontSize:22,fontWeight:700,marginTop:9,marginBottom:8},meta:{fontSize:8,color:"#525252",marginTop:2},logo:{width:140,height:55,objectFit:"contain"},grid:{flexDirection:"row",gap:24,marginTop:20},col:{width:"50%"},label:{fontSize:8,fontWeight:700,color:"#737373",marginBottom:5},strong:{fontWeight:700,marginBottom:3},body:{lineHeight:1.55,whiteSpace:"pre-wrap"},intro:{marginTop:20},section:{marginTop:18},heading:{fontSize:12,fontWeight:700,borderBottomWidth:1,borderBottomColor:"#d4d4d4",paddingBottom:5,marginBottom:7},row:{flexDirection:"row",justifyContent:"space-between",borderBottomWidth:.5,borderBottomColor:"#e5e5e5",paddingVertical:5},total:{fontSize:12,fontWeight:700,textAlign:"right",marginTop:9},footer:{marginTop:28,borderTopWidth:1,borderTopColor:"#d4d4d4",paddingTop:14},signature:{fontWeight:700,marginTop:20}});
