"use client";

import { useState } from "react";
import { ArrowLeft, ChevronRight, Circle, CircleDot, CheckCircle2 } from "lucide-react";
import BidScheduleWorkItem, { CompletionBadge, completionFromBilling, type BidWorkItem } from "@/components/BidScheduleWorkItem";

export default function BidScheduleOfWork({ bidId, initialItems, canWrite, addForm }: { bidId: string; initialItems: BidWorkItem[]; canWrite: boolean; addForm?: React.ReactNode }) {
  const [items, setItems] = useState(initialItems); const [selectedId, setSelectedId] = useState<string | null>(null); const selected = items.find((item) => item.id === selectedId);
  const scheduled = items.reduce((sum, item) => sum + Number(item.scheduled_value || 0), 0); const billed = items.reduce((sum, item) => sum + billingTotal(item), 0); const completed = items.filter((item) => billingStatus(item) === "completed").length; const partial = items.filter((item) => billingStatus(item) === "partially_completed").length;
  const progress = scheduled > 0 ? Math.min(100, Math.max(0, Math.round((billed / scheduled) * 1000) / 10)) : 0;
  if (selected) return <div className="space-y-4"><button type="button" onClick={() => setSelectedId(null)} className="inline-flex items-center gap-2 text-sm font-semibold text-neutral-400 hover:text-white"><ArrowLeft className="h-4 w-4" />Back to full schedule</button><BidScheduleWorkItem bidId={bidId} item={selected} displayNumber={items.findIndex((item) => item.id === selected.id) + 1} canWrite={canWrite} onSaved={(changes) => setItems((current) => current.map((item) => item.id === selected.id ? { ...item, ...changes } : item))} onRemoved={() => { setItems((current) => current.filter((item) => item.id !== selected.id)); setSelectedId(null); }} /></div>;
  return <div className="space-y-5"><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Schedule of Work</h2><p className="mt-2 max-w-3xl text-sm text-neutral-400">Review operational completion and progressive billing across the full schedule. Select a line for billing details and documentation.</p></div><div className="min-w-36 rounded-xl border border-white/10 bg-black/10 px-4 py-3 text-right"><p className="text-2xl font-semibold text-white">{progress}%</p><p className="text-xs text-neutral-500">total completion</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#fb5411] transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-neutral-500"><span>{items.length} total line items</span><span>{completed} complete</span><span>{partial} partially complete</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Scheduled value" value={currency(scheduled)} /><Summary label="Total billed" value={currency(billed)} accent /><Summary label="Completed" value={`${completed} items`} /><Summary label="Partially completed" value={`${partial} items`} /></div></section><ScheduleList items={items} onSelect={setSelectedId} />{canWrite && addForm}</div>;
}

function ScheduleList({ items, onSelect }: { items: BidWorkItem[]; onSelect: (id: string) => void }) {
  if (!items.length) return <section className="rounded-2xl border border-dashed border-white/15 p-10 text-center text-sm text-neutral-500">No schedule line items have been entered.</section>;
  return <section className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="hidden grid-cols-[70px_minmax(280px,1fr)_150px_160px_100px_150px_24px] gap-3 border-b border-white/10 px-5 py-3 text-xs uppercase tracking-[0.1em] text-neutral-500 xl:grid"><span>Item</span><span>Description</span><span>Scheduled</span><span>Billing status</span><span>%</span><span>Balance</span><span /></div><div className="divide-y divide-white/10">{items.map((item, index) => { const total = billingTotal(item); const scheduled = Number(item.scheduled_value || 0); const percent = scheduled === 0 ? 0 : Math.round((total / scheduled) * 1000) / 10; const status = billingStatus(item); return <button type="button" key={item.id} onClick={() => onSelect(item.id)} className="grid w-full gap-3 px-4 py-4 text-left transition hover:bg-white/[0.05] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#fb5411] sm:px-5 xl:grid-cols-[70px_minmax(280px,1fr)_150px_160px_100px_150px_24px] xl:items-center"><span className="text-sm text-neutral-500">{item.item_number || index + 1}</span><div className="flex min-w-0 items-start gap-3"><CompletionIcon status={status} /><div className="min-w-0"><p className="text-sm font-medium text-white">{item.description}</p><p className="mt-1 text-xs text-neutral-500">{item.item_type === "change_order" ? item.change_order_number || "Change order" : "Original contract"}</p></div></div><span className="text-sm text-neutral-300">{currency(scheduled)}</span><CompletionBadge status={status} /><span className="text-sm font-semibold text-neutral-300">{percent}%</span><span className="text-sm text-neutral-300">{currency(scheduled - total)}</span><ChevronRight className="hidden h-4 w-4 text-neutral-600 xl:block" /></button>; })}</div></section>;
}
function CompletionIcon({ status }: { status: BidWorkItem["completion_status"] }) { if (status === "completed") return <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#fb5411]" />; if (status === "partially_completed") return <CircleDot className="mt-0.5 h-4 w-4 shrink-0 text-[#fb5411]" />; return <Circle className="mt-0.5 h-4 w-4 shrink-0 text-neutral-600" />; }
function Summary({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`rounded-xl border p-3 ${accent ? "border-[#fb5411]/40 bg-[#fb5411]/10" : "border-white/10 bg-black/15"}`}><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>; }
function billingTotal(item: BidWorkItem) { return Number(item.previous_billing || 0) + Number(item.current_billing || 0) + Number(item.stored_materials || 0); }
function billingStatus(item: BidWorkItem) { return completionFromBilling(Number(item.scheduled_value || 0), billingTotal(item)); }
function currency(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }
