"use client";

import { useEffect, useRef, useState } from "react";
import { Check, ChevronDown, LoaderCircle, Trash2 } from "lucide-react";

export type CompletionStatus = "not_completed" | "partially_completed" | "completed";
export type BidWorkItem = {
  id: string; item_number: string | null; description: string; scheduled_value: number | null; notes: string | null;
  item_type: "original_contract" | "change_order"; change_order_number: string | null;
  change_order_approval_status: ChangeOrderStatus | null; change_order_approved_at: string | null;
  completion_status: CompletionStatus; previous_billing: number; current_billing: number; stored_materials: number;
  retainage_amount: number; billing_application_number: string | null; billing_period_to: string | null; billing_source_document: string | null;
};
type ChangeOrderStatus = "proposed" | "pending_approval" | "approved" | "rejected";
type Draft = { description: string; scheduledValue: string; notes: string; itemType: "original_contract" | "change_order"; changeOrderNumber: string; changeOrderApprovalStatus: ChangeOrderStatus; changeOrderApprovedAt: string; previousBilling: string; currentBilling: string; storedMaterials: string; retainageAmount: string; billingApplicationNumber: string; billingPeriodTo: string; billingSourceDocument: string };
const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-white/10 bg-neutral-900 px-3 text-sm text-white outline-none focus:border-[#fb5411] disabled:opacity-70";
const selectClass = `${inputClass} appearance-none pr-11`;

export default function BidScheduleWorkItem({ bidId, item, displayNumber, canWrite, onSaved, onRemoved }: { bidId: string; item: BidWorkItem; displayNumber: number; canWrite: boolean; onSaved: (changes: Partial<BidWorkItem>) => void; onRemoved: () => void }) {
  const [draft, setDraft] = useState<Draft>(() => toDraft(item));
  const [state, setState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [error, setError] = useState(""); const initialized = useRef(false); const saved = useRef(onSaved);
  useEffect(() => { saved.current = onSaved; }, [onSaved]);
  useEffect(() => { if (!canWrite) return; if (!initialized.current) { initialized.current = true; return; } setState("saving"); setError(""); const controller = new AbortController(); const timer = window.setTimeout(async () => { try { const response = await fetch(`/api/admin/bids/${encodeURIComponent(bidId)}/work-items/${encodeURIComponent(item.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft), signal: controller.signal }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "Unable to save this line item."); setState("saved"); saved.current(draftToItem(draft)); } catch (saveError) { if (controller.signal.aborted) return; setState("error"); setError(saveError instanceof Error ? saveError.message : "Unable to save this line item."); } }, 550); return () => { window.clearTimeout(timer); controller.abort(); }; }, [bidId, canWrite, draft, item.id]);
  async function remove() { if (!window.confirm("Remove this schedule line item? Calendar events connected to it will also be removed.")) return; setState("saving"); const response = await fetch(`/api/admin/bids/${encodeURIComponent(bidId)}/work-items/${encodeURIComponent(item.id)}`, { method: "DELETE" }); const body = await response.json().catch(() => null); if (!response.ok) { setState("error"); setError(body?.error || "Unable to remove this line item."); return; } onRemoved(); }
  const update = (changes: Partial<Draft>) => setDraft((current) => ({ ...current, ...changes }));
  const scheduled = money(draft.scheduledValue), previous = money(draft.previousBilling), current = money(draft.currentBilling), stored = money(draft.storedMaterials), total = previous + current + stored, balance = scheduled - total, percent = scheduled === 0 ? 0 : Math.round((total / scheduled) * 1000) / 10, completionStatus = completionFromBilling(scheduled, total);
  return <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.14em] text-[#ff8a5b]">Schedule Line {item.item_number || displayNumber}</p><h2 className="mt-1 text-xl font-semibold">{draft.description}</h2></div><CompletionBadge status={completionStatus} /></div>
    <div className="mt-5 grid gap-3 md:grid-cols-[minmax(0,1fr)_170px]"><Field label="Description"><input value={draft.description} onChange={(event) => update({ description: event.target.value })} disabled={!canWrite} className={inputClass} /></Field><Field label="Scheduled value"><CurrencyInput value={draft.scheduledValue} onChange={(scheduledValue) => update({ scheduledValue })} disabled={!canWrite} /></Field></div>
    <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Item type"><Select value={draft.itemType} onChange={(itemType) => update({ itemType: itemType as Draft["itemType"] })} disabled={!canWrite}><option value="original_contract">Original Contract</option><option value="change_order">Change Order</option></Select></Field>{draft.itemType === "change_order" && <><Field label="Change order number"><input value={draft.changeOrderNumber} onChange={(event) => update({ changeOrderNumber: event.target.value })} disabled={!canWrite} className={inputClass} /></Field><Field label="Approval status"><Select value={draft.changeOrderApprovalStatus} onChange={(changeOrderApprovalStatus) => update({ changeOrderApprovalStatus: changeOrderApprovalStatus as ChangeOrderStatus })} disabled={!canWrite}><option value="proposed">Proposed</option><option value="pending_approval">Pending Approval</option><option value="approved">Approved</option><option value="rejected">Rejected</option></Select></Field></>}</div>
    <div className="mt-5 rounded-xl border border-white/10 bg-black/15 p-4"><h3 className="font-semibold">Billing progression</h3><p className="mt-1 text-xs text-neutral-500">Track earned billing independently from operational completion.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Field label="Previous billing"><CurrencyInput value={draft.previousBilling} onChange={(previousBilling) => update({ previousBilling })} disabled={!canWrite} /></Field><Field label="Current billing"><CurrencyInput value={draft.currentBilling} onChange={(currentBilling) => update({ currentBilling })} disabled={!canWrite} /></Field><Field label="Stored materials"><CurrencyInput value={draft.storedMaterials} onChange={(storedMaterials) => update({ storedMaterials })} disabled={!canWrite} /></Field><Field label="Retainage"><CurrencyInput value={draft.retainageAmount} onChange={(retainageAmount) => update({ retainageAmount })} disabled={!canWrite} /></Field><Field label="Total billed"><Readout value={currency(total)} /></Field></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Percent complete" value={`${percent}%`} /><Metric label="Balance to finish" value={currency(balance)} /><Metric label="Earned less retainage" value={currency(total - money(draft.retainageAmount))} /></div></div>
    <div className="mt-5 rounded-xl border border-white/10 bg-black/15 p-4"><h3 className="font-semibold">Billing reference</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Application / invoice number"><input value={draft.billingApplicationNumber} onChange={(event) => update({ billingApplicationNumber: event.target.value })} disabled={!canWrite} placeholder="Example: Pay App #9" className={inputClass} /></Field><Field label="Period to"><input type="date" value={draft.billingPeriodTo} onChange={(event) => update({ billingPeriodTo: event.target.value })} disabled={!canWrite} className={inputClass} /></Field><Field label="Source document"><input value={draft.billingSourceDocument} onChange={(event) => update({ billingSourceDocument: event.target.value })} disabled={!canWrite} placeholder="Payment application filename" className={inputClass} /></Field></div></div>
    <Field label="Notes"><textarea rows={3} value={draft.notes} onChange={(event) => update({ notes: event.target.value })} disabled={!canWrite} className={`${inputClass} mt-4 h-auto py-2.5`} /></Field>
    {canWrite && <div className="mt-4 flex min-h-7 items-center justify-between gap-3"><button type="button" onClick={() => void remove()} disabled={state === "saving"} className="inline-flex items-center gap-2 text-sm font-semibold text-red-300 disabled:opacity-50"><Trash2 className="h-4 w-4" />Remove</button><span className={`inline-flex items-center gap-1.5 text-xs ${state === "error" ? "text-red-300" : "text-neutral-500"}`}>{state === "saving" && <><LoaderCircle className="h-3.5 w-3.5 animate-spin" />Saving…</>}{state === "saved" && <><Check className="h-3.5 w-3.5 text-emerald-400" />Saved</>}{state === "error" && error}</span></div>}
  </section>;
}

export function CompletionBadge({ status }: { status: CompletionStatus }) { const label = status === "completed" ? "Completed" : status === "partially_completed" ? "Partially Completed" : "Not Completed"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${status === "completed" ? "border-[#fb5411]/30 bg-[#fb5411]/10 text-[#ff8a5b]" : status === "partially_completed" ? "border-white/20 bg-white/[0.06] text-neutral-200" : "border-white/10 text-neutral-500"}`}>{label}</span>; }
export function NewScheduleCurrencyInput() { const [value, setValue] = useState(""); return <CurrencyInput name="scheduled_value" value={value} onChange={setValue} disabled={false} placeholder="$0.00" />; }
function CurrencyInput({ value, onChange, disabled, name, placeholder }: { value: string; onChange: (value: string) => void; disabled: boolean; name?: string; placeholder?: string }) { const [focused, setFocused] = useState(false); const numeric = Number(value); const display = !focused && /^-?\d+(\.\d+)?$/.test(value) && Number.isFinite(numeric) ? currency(numeric) : value; return <input name={name} type="text" inputMode="decimal" value={display} placeholder={placeholder} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} onChange={(event) => { const next = event.target.value.replace(/[$,\s]/g, ""); if (/^-?\d*(\.\d{0,2})?$/.test(next)) onChange(next); }} disabled={disabled} className={inputClass} />; }
function Select({ value, onChange, disabled, children }: { value: string; onChange: (value: string) => void; disabled: boolean; children: React.ReactNode }) { return <span className="relative block"><select value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} className={selectClass}>{children}</select><ChevronDown className="pointer-events-none absolute bottom-3.5 right-4 h-4 w-4 text-neutral-500" /></span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs text-neutral-400">{label}{children}</label>; }
function Readout({ value }: { value: string }) { return <div className={`${inputClass} flex items-center bg-white/[0.04] text-neutral-300`}>{value}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/10 p-3"><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>; }
function toDraft(item: BidWorkItem): Draft { return { description: item.description, scheduledValue: String(item.scheduled_value ?? ""), notes: item.notes || "", itemType: item.item_type || "original_contract", changeOrderNumber: item.change_order_number || "", changeOrderApprovalStatus: item.change_order_approval_status || "proposed", changeOrderApprovedAt: item.change_order_approved_at || "", previousBilling: String(item.previous_billing || 0), currentBilling: String(item.current_billing || 0), storedMaterials: String(item.stored_materials || 0), retainageAmount: String(item.retainage_amount || 0), billingApplicationNumber: item.billing_application_number || "", billingPeriodTo: item.billing_period_to || "", billingSourceDocument: item.billing_source_document || "" }; }
function draftToItem(draft: Draft): Partial<BidWorkItem> { const scheduled = money(draft.scheduledValue), previous = money(draft.previousBilling), current = money(draft.currentBilling), stored = money(draft.storedMaterials); return { description: draft.description, scheduled_value: scheduled, notes: draft.notes || null, item_type: draft.itemType, change_order_number: draft.itemType === "change_order" ? draft.changeOrderNumber : null, change_order_approval_status: draft.itemType === "change_order" ? draft.changeOrderApprovalStatus : null, completion_status: completionFromBilling(scheduled, previous + current + stored), previous_billing: previous, current_billing: current, stored_materials: stored, retainage_amount: money(draft.retainageAmount), billing_application_number: draft.billingApplicationNumber || null, billing_period_to: draft.billingPeriodTo || null, billing_source_document: draft.billingSourceDocument || null }; }
export function completionFromBilling(scheduled: number, total: number): CompletionStatus { if (Math.abs(total) < 0.005 || Math.abs(scheduled) < 0.005) return "not_completed"; return Math.abs(total) >= Math.abs(scheduled) - 0.01 ? "completed" : "partially_completed"; }
function money(value: string) { const result = Number(value || 0); return Number.isFinite(result) ? result : 0; }
function currency(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }
