import { saveJobPosting } from "@/app/admin/applications/actions";
import type { JobPosting } from "@/lib/careers";
import FormattingTextarea from "@/components/FormattingTextarea";

export default function JobPostingForm({ job }: { job?: JobPosting & { status?: string } }) {
  return <form action={saveJobPosting.bind(null, job?.id || null)} className="mt-8 space-y-6 rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><Field name="title" label="Job title" required defaultValue={job?.title} /><Field name="slug" label="URL slug" required defaultValue={job?.slug} help="Lowercase letters, numbers, and hyphens." /><Field name="location" label="Location" required defaultValue={job?.location} /><Select name="employment_type" label="Employment type" defaultValue={job?.employment_type || "full_time"} options={["full_time","part_time","contract","temporary","internship"]} /><Field name="compensation" label="Compensation" defaultValue={job?.compensation || ""} /><Select name="status" label="Posting status" defaultValue={job?.status || "draft"} options={["draft","published","closed"]} /><Field name="tags" label="Filter tags" defaultValue={job?.tags?.join(", ")} wide help="Separate tags with commas, such as Operations, Sales, Remote." /><Area name="summary" label="Short summary" required defaultValue={job?.summary} formatting={false} /><Area name="description" label="Full description" required defaultValue={job?.description} /><Area name="responsibilities" label="Responsibilities" defaultValue={job?.responsibilities?.join("\n")} help="Enter one responsibility per line." /><Area name="qualifications" label="Qualifications" defaultValue={job?.qualifications?.join("\n")} help="Enter one qualification per line." /></div><button className="rounded-xl bg-[#fb5411] px-5 py-3 text-sm font-semibold text-white">{job ? "Save job posting" : "Create job posting"}</button></form>;
}
const input = "mt-2 h-12 w-full rounded-xl border border-white/10 bg-neutral-900 px-4 text-white outline-none focus:border-[#fb5411]";
function Field({ label, wide, help, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; wide?: boolean; help?: string }) { return <label className={`text-sm text-neutral-300 ${wide ? "sm:col-span-2" : ""}`}>{label}{props.required && " *"}<input {...props} className={input} />{help && <span className="mt-1 block text-xs text-neutral-500">{help}</span>}</label>; }
function Area({ label, name, required, defaultValue, help, formatting = true }: { label: string; name: string; required?: boolean; defaultValue?: string | null; help?: string; formatting?: boolean }) { return <label className="text-sm text-neutral-300 sm:col-span-2">{label}{required && " *"}{formatting ? <FormattingTextarea name={name} required={required} defaultValue={defaultValue || ""} /> : <textarea name={name} required={required} defaultValue={defaultValue || ""} rows={3} className={`${input} h-auto py-3`} />}{help && <span className="mt-1 block text-xs text-neutral-500">{help}</span>}</label>; }
function Select({ label, name, defaultValue, options }: { label: string; name: string; defaultValue: string; options: string[] }) { return <label className="text-sm text-neutral-300">{label}<select name={name} defaultValue={defaultValue} className={`${input} pr-12 capitalize`}>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>; }
